In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('dataset.csv')

In [5]:
df.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34886 entries, 0 to 34885
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Release Year      34886 non-null  int64
 1   Title             34886 non-null  object
 2   Origin/Ethnicity  34886 non-null  object
 3   Director          34886 non-null  object
 4   Cast              33464 non-null  object
 5   Genre             34886 non-null  object
 6   Wiki Page         34886 non-null  object
 7   Plot              34886 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.1+ MB

In [7]:
df['Plot'][0]

"A bartender is working at a saloon, serving drinks to customers. After he fills a stereotypically Irish man's bucket with beer, Carrie Nation and her followers burst inside. They assault the Irish man, pulling his hat over his eyes and then dumping the beer over his head. The group then begin wrecking the bar, smashing the fixtures, mirrors, and breaking the cash register. The bartender then sprays seltzer water in Nation's face before a group of policemen appear and order everybody to leave.[1]"

In [8]:
df['Wiki Page'][0]

'https://en.wikipedia.org/wiki/Kansas_Saloon_Smashers'

In [9]:
df['Genre'].isna()

0        False
1        False
2        False
3        False
4        False
         ...
34881    False
34882    False
34883    False
34884    False
34885    False
Name: Genre, Length: 34886, dtype: bool

In [10]:
df.isna().sum()

Release Year           0
Title                  0
Origin/Ethnicity       0
Director               0
Cast                1422
Genre                  0
Wiki Page              0
Plot                   0
dtype: int64

In [11]:
df.describe()

       Release Year
count  34886.000000
mean    1981.314252
std       27.815174
min     1901.000000
25%     1957.000000
50%     1988.000000
75%     2007.000000
max     2017.000000

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['Release Year'].value_counts()

Release Year
2013    1021
2014     929
2012     874
2011     858
2010     825
        ...
1906       3
1905       2
1903       2
1904       1
1902       1
Name: count, Length: 117, dtype: int64

In [14]:
df['Title'].value_counts()

Title
Cinderella               8
The Three Musketeers     8
Treasure Island          7
Hero                     6
Alice in Wonderland      6
                        ..
Leap of Faith            1
A League of Their Own    1
The Lawnmower Man        1
Ladybugs                 1
İstanbul Kırmızısı       1
Name: count, Length: 32432, dtype: int64

In [15]:
df['Origin/Ethnicity'].value_counts()

Origin/Ethnicity
American        17377
British          3670
Bollywood        2931
Tamil            2599
Telugu           1311
Japanese         1188
Malayalam        1095
Hong Kong         791
Canadian          723
Australian        576
South_Korean      522
Chinese           463
Kannada           444
Bengali           306
Russian           232
Marathi           141
Filipino          128
Bangladeshi        87
Punjabi            84
Malaysian          70
Turkish            70
Egyptian           67
Assamese            9
Maldivian           2
Name: count, dtype: int64

In [16]:
df['Director'].value_counts()

Director
Unknown                1124
Michael Curtiz           79
Hanna-Barbera            77
Lloyd Bacon              66
Jules White              63
                       ...
Brian Clemens             1
Lester James Peries       1
Maurice Hamblin           1
Trevor Wrenn              1
Ferzan Özpetek            1
Name: count, Length: 12593, dtype: int64

In [17]:
df['Genre'].value_counts()

Genre
unknown                          6083
drama                            5964
comedy                           4379
horror                           1167
action                           1098
                                 ...
cbc-tv miniseries                   1
bio-drama                           1
national film board docudrama       1
cult drama                          1
horror romantic comedy              1
Name: count, Length: 2265, dtype: int64

In [18]:
df['Wiki Page'].value_counts()

Wiki Page
https://en.wikipedia.org/wiki/Digimon_Adventure_tri.                         5
https://en.wikipedia.org/wiki/Himitsu_Sentai_Gorenger                        5
https://en.wikipedia.org/wiki/Tamayura                                       4
https://en.wikipedia.org/wiki/Mani_Malai                                     4
https://en.wikipedia.org/wiki/Vettaikaaran_(2009_film)                       3
                                                                            ..
https://en.wikipedia.org/wiki/Hot_Cars,_Cold_Facts                           1
https://en.wikipedia.org/wiki/Home_Alone                                     1
https://en.wikipedia.org/wiki/Heart_Condition_(film)                         1
https://en.wikipedia.org/wiki/Havana_(film)                                  1
https://en.wikipedia.org/wiki/%C4%B0stanbul_K%C4%B1rm%C4%B1z%C4%B1s%C4%B1    1
Name: count, Length: 34070, dtype: int64

In [19]:
(df['Plot'].isna() == True).sum()

np.int64(0)

In [21]:
df1 = df.copy()
df1.replace(['unknown','Unknown',''], np.nan, inplace=True)

In [22]:
df.nunique()

Release Year          117
Title               32432
Origin/Ethnicity       24
Director            12593
Cast                32182
Genre                2265
Wiki Page           34070
Plot                33869
dtype: int64